# Generated by Django 5.2.4 on 2025-09-26 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_uniq_review_per_user_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfollows',
            index=models.Index(fields=['user'], name='reviews_use_user_id_fec23f_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollows',
            index=models.Index(fields=['followed_user'], name='reviews_use_followe_ff5d5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollows',
            constraint=models.UniqueConstraint(fields=('user', 'followed_user'), name='unique_follow_relation'),
        ),
    ]
